# Amira Project 611
# Amira
# Generated by Amira 6.1.1
remove -all
remove "physics.icol" "tracksMeasured_t_0047.am" "tracks_t_0047.am" "Spatial Graph View" "Spatial Graph View 2" "Time Series Control 3" "Time Series Control 4"

# Create viewers
viewer setVertical 0

viewer 0 setTransparencyType 4
viewer 0 setAutoRedraw 0
viewer 0 show
mainWindow show

set hideNewModules 0
[ load ${AMIRA_ROOT}/data/colormaps/physics.icol ] setLabel "physics.icol"
"physics.icol" setIconPosition 598 194
"physics.icol" setNoRemoveAll 1
"physics.icol" master disconnect
"physics.icol" Datafield disconnect
"physics.icol" fire
"physics.icol" setMinMax 0 50
"physics.icol" flags setValue 1
"physics.icol" shift setMinMax -1 1
"physics.icol" shift setButtons 0
"physics.icol" shift setEditButton 1
"physics.icol" shift setIncrement 0.133333
"physics.icol" shift setValue -0.261146
"physics.icol" shift setSubMinMax -1 1
"physics.icol" scale setMinMax 0 1
"physics.icol" scale setButtons 0
"physics.icol" scale setEditButton 1
"physics.icol" scale setIncrement 0.1
"physics.icol" scale setValue 1
"physics.icol" scale setSubMinMax 0 1
"physics.icol" fire
"physics.icol" setViewerMask 16383

set hideNewModules 0
create HxDynamicFileSeriesCtrl "Time Series Control 4"
"Time Series Control 4" setIconPosition 13 46
"Time Series Control 4" init -loadCmd {load "$FILENAME"} \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0001.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0002.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0003.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0004.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0005.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0006.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0007.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0008.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0009.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0010.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0011.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0012.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0013.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0014.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0015.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0016.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0017.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0018.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0019.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0020.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0021.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0022.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0023.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0024.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0025.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0026.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0027.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0028.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0029.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0030.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0031.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0032.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0033.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0034.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0035.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0036.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0037.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0038.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0039.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0040.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0041.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0042.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0043.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0044.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0045.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0046.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0047.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0048.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0049.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0050.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0051.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0052.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0053.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0054.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0055.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0056.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0057.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0058.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0059.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0060.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0061.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0062.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0063.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0064.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0065.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0066.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0067.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0068.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0069.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0070.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0071.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0072.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0073.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0074.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0075.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0076.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0077.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0078.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0079.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0080.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0081.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0082.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0083.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0084.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0085.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0086.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0087.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0088.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0089.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0090.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0091.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0092.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0093.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0094.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0095.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0096.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0097.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0098.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0099.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0100.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0101.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0102.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0103.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0104.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0105.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0106.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0107.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0108.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0109.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0110.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0111.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0112.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0113.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0114.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0115.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0116.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0117.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0118.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0119.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0120.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0121.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0122.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0123.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0124.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0125.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0126.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0127.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0128.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0129.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0130.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0131.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0132.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0133.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0134.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0135.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0136.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0137.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0138.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0139.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0140.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0141.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0142.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0143.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0144.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0145.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0146.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0147.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0148.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0149.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0150.am"
"Time Series Control 4" cachedSteps setMinMax 0 0 150
"Time Series Control 4" cachedSteps setValue 0 150
"Time Series Control 4" options setValue 0 0
"Time Series Control 4" options setToggleVisible 0 1
"Time Series Control 4" options setValue 1 0
"Time Series Control 4" options setToggleVisible 1 1
"Time Series Control 4" options setValue 2 0
"Time Series Control 4" options setToggleVisible 2 1
"Time Series Control 4" options setValue 3 0
"Time Series Control 4" options setToggleVisible 3 1
"Time Series Control 4" fire
"Time Series Control 4" time disconnect
"Time Series Control 4" time setMinMax 0 149
"Time Series Control 4" time setSubMinMax 0 149
"Time Series Control 4" time setValue 46
"Time Series Control 4" time setDiscrete 1
"Time Series Control 4" time setIncrement 1
"Time Series Control 4" time animationMode -loop
"Time Series Control 4" applyTransformToResult 1
"Time Series Control 4" fire
"Time Series Control 4" setViewerMask 16383
"Time Series Control 4" select
"Time Series Control 4" time setPin 1
"Time Series Control 4" setPickable 1

set hideNewModules 0
[ load ${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraMeasured/tracksMeasured_t_0047.am ] setLabel "tracksMeasured_t_0047.am"
"tracksMeasured_t_0047.am" setIconPosition 192 74
"tracksMeasured_t_0047.am" master connect "Time Series Control 4" "result" 0
"tracksMeasured_t_0047.am" fire
"tracksMeasured_t_0047.am" fire
"tracksMeasured_t_0047.am" setViewerMask 16383

set hideNewModules 0
create HxSpatialGraphView "Spatial Graph View 2"
"Spatial Graph View 2" setIconPosition 689 46
"Spatial Graph View 2" setVar "CustomHelp" {HxSpatialGraphView}
"Spatial Graph View 2" data connect "tracksMeasured_t_0047.am"
"Spatial Graph View 2" Statistics disconnect
"Spatial Graph View 2" nodeColormap connect "physics.icol"
"Spatial Graph View 2" nodeColormap setDefaultColor 1 0.8 0.5
"Spatial Graph View 2" nodeColormap setDefaultAlpha 0.500000
"Spatial Graph View 2" nodeColormap setLocalRange 1
"Spatial Graph View 2" nodeColormap setLocalMinMax 0.000000 1.000000
"Spatial Graph View 2" nodeColormap enableAlpha 1
"Spatial Graph View 2" nodeColormap enableAlphaToggle 1
"Spatial Graph View 2" nodeColormap setAutoAdjustRangeMode 1
"Spatial Graph View 2" nodeColormap setColorbarMinMax 0 120
"Spatial Graph View 2" segmentColormap connect "physics.icol"
"Spatial Graph View 2" segmentColormap setDefaultColor 1 0.8 0.5
"Spatial Graph View 2" segmentColormap setDefaultAlpha 0.500000
"Spatial Graph View 2" segmentColormap setLocalRange 1
"Spatial Graph View 2" segmentColormap setLocalMinMax 0.000000 1.000000
"Spatial Graph View 2" segmentColormap enableAlpha 1
"Spatial Graph View 2" segmentColormap enableAlphaToggle 1
"Spatial Graph View 2" segmentColormap setAutoAdjustRangeMode 1
"Spatial Graph View 2" segmentColormap setColorbarMinMax 0 120
"Spatial Graph View 2" fire
"Spatial Graph View 2" itemsToShow setValue 0 1
"Spatial Graph View 2" itemsToShow setToggleVisible 0 1
"Spatial Graph View 2" itemsToShow setValue 1 1
"Spatial Graph View 2" itemsToShow setToggleVisible 1 1
"Spatial Graph View 2" nodeScale setIndex 0 0
"Spatial Graph View 2" nodeScaleFactor setMinMax 0 0.100000001490116
"Spatial Graph View 2" nodeScaleFactor setButtons 0
"Spatial Graph View 2" nodeScaleFactor setEditButton 1
"Spatial Graph View 2" nodeScaleFactor setIncrement 0.00666667
"Spatial Graph View 2" nodeScaleFactor setValue 0.005
"Spatial Graph View 2" nodeScaleFactor setSubMinMax 0 0.100000001490116
"Spatial Graph View 2" nodeColoring setIndex 0 0
"Spatial Graph View 2" nodeLabelColoringOptions setValue 0
"Spatial Graph View 2" nodeColor setColor 0 0.8 0.8 0.8
"Spatial Graph View 2" segmentStyle setValue 0 0
"Spatial Graph View 2" segmentStyle setToggleVisible 0 1
"Spatial Graph View 2" segmentStyle setValue 1 0
"Spatial Graph View 2" segmentStyle setToggleVisible 1 1
"Spatial Graph View 2" segmentStyle setValue 2 1
"Spatial Graph View 2" segmentStyle setToggleVisible 2 1
"Spatial Graph View 2" tubeScale setIndex 0 0
"Spatial Graph View 2" tubeScaleFactor setMinMax 0 0.100000001490116
"Spatial Graph View 2" tubeScaleFactor setButtons 0
"Spatial Graph View 2" tubeScaleFactor setEditButton 1
"Spatial Graph View 2" tubeScaleFactor setIncrement 0.00666667
"Spatial Graph View 2" tubeScaleFactor setValue 0.1
"Spatial Graph View 2" tubeScaleFactor setSubMinMax 0 0.100000001490116
"Spatial Graph View 2" segmentWidth setMinMax 0 10
"Spatial Graph View 2" segmentWidth setButtons 0
"Spatial Graph View 2" segmentWidth setEditButton 1
"Spatial Graph View 2" segmentWidth setIncrement 0.666667
"Spatial Graph View 2" segmentWidth setValue 1
"Spatial Graph View 2" segmentWidth setSubMinMax 0 10
"Spatial Graph View 2" segmentColoring setIndex 0 2
"Spatial Graph View 2" segmentLabelColoringOptions setValue 0
"Spatial Graph View 2" segmentColor setColor 0 0.8 0.8 0.8
"Spatial Graph View 2" pointSize setMinMax 0 15
"Spatial Graph View 2" pointSize setButtons 0
"Spatial Graph View 2" pointSize setEditButton 1
"Spatial Graph View 2" pointSize setIncrement 1
"Spatial Graph View 2" pointSize setValue 4
"Spatial Graph View 2" pointSize setSubMinMax 0 15
"Spatial Graph View 2" setVisibility HIJMPLPPBPACAACDOEAHPJ HIJMPLPPBPBFAAAAIHIIAPPB
"Spatial Graph View 2" fire
"Spatial Graph View 2" setViewerMask 16383
"Spatial Graph View 2" setPickable 1

set hideNewModules 0
create HxDynamicFileSeriesCtrl "Time Series Control 3"
"Time Series Control 3" setIconPosition 42 142
"Time Series Control 3" init -loadCmd {load "$FILENAME"} \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0001.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0002.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0003.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0004.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0005.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0006.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0007.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0008.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0009.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0010.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0011.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0012.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0013.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0014.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0015.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0016.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0017.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0018.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0019.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0020.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0021.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0022.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0023.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0024.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0025.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0026.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0027.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0028.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0029.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0030.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0031.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0032.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0033.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0034.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0035.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0036.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0037.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0038.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0039.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0040.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0041.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0042.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0043.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0044.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0045.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0046.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0047.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0048.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0049.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0050.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0051.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0052.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0053.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0054.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0055.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0056.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0057.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0058.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0059.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0060.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0061.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0062.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0063.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0064.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0065.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0066.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0067.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0068.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0069.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0070.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0071.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0072.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0073.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0074.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0075.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0076.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0077.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0078.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0079.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0080.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0081.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0082.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0083.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0084.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0085.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0086.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0087.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0088.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0089.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0090.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0091.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0092.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0093.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0094.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0095.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0096.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0097.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0098.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0099.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0100.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0101.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0102.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0103.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0104.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0105.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0106.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0107.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0108.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0109.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0110.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0111.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0112.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0113.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0114.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0115.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0116.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0117.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0118.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0119.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0120.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0121.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0122.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0123.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0124.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0125.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0126.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0127.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0128.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0129.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0130.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0131.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0132.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0133.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0134.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0135.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0136.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0137.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0138.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0139.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0140.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0141.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0142.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0143.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0144.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0145.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0146.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0147.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0148.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0149.am" \
"${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0150.am"
"Time Series Control 3" cachedSteps setMinMax 0 0 150
"Time Series Control 3" cachedSteps setValue 0 150
"Time Series Control 3" options setValue 0 0
"Time Series Control 3" options setToggleVisible 0 1
"Time Series Control 3" options setValue 1 0
"Time Series Control 3" options setToggleVisible 1 1
"Time Series Control 3" options setValue 2 0
"Time Series Control 3" options setToggleVisible 2 1
"Time Series Control 3" options setValue 3 0
"Time Series Control 3" options setToggleVisible 3 1
"Time Series Control 3" fire
"Time Series Control 3" time connect "Time Series Control 4"
"Time Series Control 3" time setMinMax 0 149
"Time Series Control 3" time setSubMinMax 0 149
"Time Series Control 3" time setValue 46
"Time Series Control 3" time setDiscrete 1
"Time Series Control 3" time setIncrement 1
"Time Series Control 3" time animationMode -loop
"Time Series Control 3" applyTransformToResult 1
"Time Series Control 3" fire
"Time Series Control 3" setViewerMask 16383
"Time Series Control 3" setPickable 1

set hideNewModules 0
[ load ${SCRIPTDIR}/scripts/simulationData/frequencyVariation/frequency_3.5/amiraSimu/tracks_t_0047.am ] setLabel "tracks_t_0047.am"
"tracks_t_0047.am" setIconPosition 20 190
"tracks_t_0047.am" master connect "Time Series Control 3" "result" 0
"tracks_t_0047.am" fire
"tracks_t_0047.am" fire
"tracks_t_0047.am" setViewerMask 16383

set hideNewModules 0
create HxSpatialGraphView "Spatial Graph View"
"Spatial Graph View" setIconPosition 374 199
"Spatial Graph View" setVar "CustomHelp" {HxSpatialGraphView}
"Spatial Graph View" data connect "tracks_t_0047.am"
"Spatial Graph View" Statistics disconnect
"Spatial Graph View" nodeColormap connect "physics.icol"
"Spatial Graph View" nodeColormap setDefaultColor 1 0.8 0.5
"Spatial Graph View" nodeColormap setDefaultAlpha 0.500000
"Spatial Graph View" nodeColormap setLocalRange 1
"Spatial Graph View" nodeColormap setLocalMinMax 0.000000 1.000000
"Spatial Graph View" nodeColormap enableAlpha 1
"Spatial Graph View" nodeColormap enableAlphaToggle 1
"Spatial Graph View" nodeColormap setAutoAdjustRangeMode 1
"Spatial Graph View" nodeColormap setColorbarMinMax 0 120
"Spatial Graph View" segmentColormap connect "physics.icol"
"Spatial Graph View" segmentColormap setDefaultColor 1 0.8 0.5
"Spatial Graph View" segmentColormap setDefaultAlpha 0.500000
"Spatial Graph View" segmentColormap setLocalRange 1
"Spatial Graph View" segmentColormap setLocalMinMax 0.000000 1.000000
"Spatial Graph View" segmentColormap enableAlpha 1
"Spatial Graph View" segmentColormap enableAlphaToggle 1
"Spatial Graph View" segmentColormap setAutoAdjustRangeMode 1
"Spatial Graph View" segmentColormap setColorbarMinMax 0 120
"Spatial Graph View" fire
"Spatial Graph View" itemsToShow setValue 0 1
"Spatial Graph View" itemsToShow setToggleVisible 0 1
"Spatial Graph View" itemsToShow setValue 1 0
"Spatial Graph View" itemsToShow setToggleVisible 1 1
"Spatial Graph View" nodeScale setIndex 0 0
"Spatial Graph View" nodeScaleFactor setMinMax 0 1
"Spatial Graph View" nodeScaleFactor setButtons 0
"Spatial Graph View" nodeScaleFactor setEditButton 1
"Spatial Graph View" nodeScaleFactor setIncrement 0.0666667
"Spatial Graph View" nodeScaleFactor setValue 0.312102
"Spatial Graph View" nodeScaleFactor setSubMinMax 0 1
"Spatial Graph View" nodeColoring setIndex 0 0
"Spatial Graph View" nodeLabelColoringOptions setValue 0
"Spatial Graph View" nodeColor setColor 0 0.8 0.8 0.8
"Spatial Graph View" segmentStyle setValue 0 0
"Spatial Graph View" segmentStyle setToggleVisible 0 1
"Spatial Graph View" segmentStyle setValue 1 0
"Spatial Graph View" segmentStyle setToggleVisible 1 1
"Spatial Graph View" segmentStyle setValue 2 0
"Spatial Graph View" segmentStyle setToggleVisible 2 1
"Spatial Graph View" tubeScale setIndex 0 0
"Spatial Graph View" tubeScaleFactor setMinMax 0 0.100000001490116
"Spatial Graph View" tubeScaleFactor setButtons 0
"Spatial Graph View" tubeScaleFactor setEditButton 1
"Spatial Graph View" tubeScaleFactor setIncrement 0.00666667
"Spatial Graph View" tubeScaleFactor setValue 0.0732484
"Spatial Graph View" tubeScaleFactor setSubMinMax 0 0.100000001490116
"Spatial Graph View" segmentWidth setMinMax 0 10
"Spatial Graph View" segmentWidth setButtons 0
"Spatial Graph View" segmentWidth setEditButton 1
"Spatial Graph View" segmentWidth setIncrement 0.666667
"Spatial Graph View" segmentWidth setValue 1
"Spatial Graph View" segmentWidth setSubMinMax 0 10
"Spatial Graph View" segmentColoring setIndex 0 0
"Spatial Graph View" segmentLabelColoringOptions setValue 0
"Spatial Graph View" segmentColor setColor 0 0.8 0.8 0.8
"Spatial Graph View" pointSize setMinMax 0 15
"Spatial Graph View" pointSize setButtons 0
"Spatial Graph View" pointSize setEditButton 1
"Spatial Graph View" pointSize setIncrement 1
"Spatial Graph View" pointSize setValue 4
"Spatial Graph View" pointSize setSubMinMax 0 15
"Spatial Graph View" setVisibility HIJMPLPPBPACAACDOEAHPJ HIJMPLPPBPBFAAAAIHIIAPPB
"Spatial Graph View" fire
"Spatial Graph View" setViewerMask 16383
"Spatial Graph View" setPickable 1

set hideNewModules 0

viewer 0 setCameraOrientation 0.989122 0.140635 0.0431125 3.18313
viewer 0 setCameraPosition 14.7463 13.3336 -43.136
viewer 0 setCameraFocalDistance 53.3735
viewer 0 setCameraNearDistance 43.0689
viewer 0 setCameraFarDistance 63.9854
viewer 0 setCameraType perspective
viewer 0 setCameraHeightAngle 44.9023
viewer 0 setAutoRedraw 1
viewer 0 redraw

theObjectPool setSelectionOrder {Time Series Control 4}
