function [ deleteLink ] = delete( clusterProfileName, ID )
%delete Return link text to delete job on clusterProfileName with ID

deleteLink = ['<a href="matlab: ' ...
    'timeCourseAnalysis.link.confirmDelete(''' ... 
    clusterProfileName ''',' ...
            num2str(ID) ')' ...
    '">Click to Delete / Cancel Job</a>'];

end

