function [ diaryLink ] = diary( clusterProfileName, ID  )
%diary Get diary link for job on clusterProfileName with ID

    diaryLink = ['<a href="matlab: diary(findJob(parcluster(''' ... 
        clusterProfileName ...
        '''),''ID'',' ...
        num2str(ID), ...
        ')),' ...
        'disp(timeCourseAnalysis.link.info(''' clusterProfileName ''',' num2str(ID) ' ));' ...
        'disp(timeCourseAnalysis.link.diary(''' clusterProfileName ''',' num2str(ID) ' ));' ...
        '">Click to Display Job Output</a>'];

end

