% [meanfMR,SEMfMR,regParams] = compareFTTC_BEM_FastBEM_fn('groupForce',3/100,...
% '/home/sh268/orchestra/home/Documents/TFM-simulation/n3g',forceMesh,forceMeshFastBEM,M,M_FastBEM,...
% '/home/sh268/orchestra/home/Documents/TFM-simulation/basisFunction5050E10kPa.mat');
% % n3g means noise= 3 percent and g = groupForce
% [meanfMRn5g,SEMfMRn5g,regParamsn5g] = compareFTTC_BEM_FastBEM_fn('groupForce',5/100,...
% '/home/sh268/orchestra/home/Documents/TFM-simulation/n5g',forceMesh,forceMeshFastBEM,M,M_FastBEM,...
% '/home/sh268/orchestra/home/Documents/TFM-simulation/basisFunction5050E10kPa.mat');
% % n1s means noise= 1 percent and g = groupForce
% 
% % For making new M and M_FastBEM 
% % For orchestra
% [meanfMRn1g,SEMfMRn1g,regParamsn1g] = compareFTTC_BEM_FastBEM_fn('groupForce',1/100,...
% '/home/sh268/Documents/TFM-simulation/n1g',forceMesh,forceMeshFastBEM,M,M_FastBEM,...
% '/home/sh268/Documents/TFM-simulation/basisFunction5050E10kPa.mat');
% % for desktop
% 
% [meanfMRn5g,SEMfMRn5g,regParamsn5g] = compareFTTC_BEM_FastBEM_fn('groupForce',5/100,...
% '/home/sh268/orchestra/home/Documents/TFM-simulation/n5g',[],forceMeshFastBEM,[],M_FastBEM,...
% '/home/sh268/orchestra/home/Documents/TFM-simulation/basisFunction5050E8000Pa.mat');
% 
% [meanfMRn10g,SEMfMRn10g,regParamsn10g] = compareFTTC_BEM_FastBEM_fn('groupForce',10/100,...
% '/home/sh268/orchestra/home/Documents/TFM-simulation/n10g',[],forceMeshFastBEM,[],M_FastBEM,...
% '/home/sh268/orchestra/home/Documents/TFM-simulation/basisFunction5050E8000Pa.mat');
% 
% [meanfMRn10g,SEMfMRn10g,regParamsn10g] = compareFTTC_BEM_FastBEM_fn('groupForce',10/100,...
% '/home/sh268/orchestra/home/Documents/TFM-simulation/n10g',forceMesh,forceMeshFastBEM,M,M_FastBEM,...
% '/home/sh268/orchestra/home/Documents/TFM-simulation/basisFunction5050E10kPa.mat');
% 
% [meanfMRn1g,SEMfMRn0g,regParamsn0g] = compareFTTC_BEM_FastBEM_fn('groupForce',0/100,...
% '/home/sh268/orchestra/home/Documents/TFM-simulation/n1g',[],[],[],[],...
% '/home/sh268/orchestra/home/Documents/TFM-simulation/basisFunction500500E8000Pa.mat');

[meanfMRn0g,SEMfMRn0g,regParamsn0g] = compareFTTC_BEM_FastBEM_fn('groupForce',0/100,...
'/home/sh268/Documents/TFM-simulation/n1g',[],[],[],[],...
'/home/sh268/Documents/TFM-simulation/basisFunction500500E8000Pa.mat');

[meanfMRn1g,SEMfMRn1g,regParamsn1g] = compareFTTC_BEM_FastBEM_fn('groupForce',1/100,...
'/home/sh268/Documents/TFM-simulation/n1g',[],forceMeshFastBEM,[],M_FastBEM,...
'/home/sh268/Documents/TFM-simulation/basisFunction500500E8000Pa.mat');

[meanfMRn5g,SEMfMRn5g,regParamsn5g] = compareFTTC_BEM_FastBEM_fn('groupForce',5/100,...
'/home/sh268/Documents/TFM-simulation/n5g',[],forceMeshFastBEM,[],M_FastBEM,...
'/home/sh268/Documents/TFM-simulation/basisFunction500500E8000Pa.mat');

[meanfMRn10g,SEMfMRn10g,regParamsn10g] = compareFTTC_BEM_FastBEM_fn('groupForce',10/100,...
'/home/sh268/Documents/TFM-simulation/n10g',[],forceMeshFastBEM,[],M_FastBEM,...
'/home/sh268/Documents/TFM-simulation/basisFunction500500E8000Pa.mat');

[pSRn5g,pSRerrn5g,regParamsn5g] = calculateForceFineMesh_fn('groupForce',5/100,...
    '/home/sh268/Documents/TFM-simulation/n5g',forceMeshFastBEM,[],M_FastBEM,[],...
    '/home/sh268/Documents/TFM-simulation/basisFunction500500E8000Pa.mat',...
    '/home/sh268/Documents/TFM-simulation/basisFunction500500E8000Pa.mat');

[pSRn5g100,pSRerrn5g100,regParamsn5g100] = calculateForceFineMeshImgScaled_fn(2,'groupForce',5/100,...
    '/home/sh268/Documents/TFM-simulation/n5g',forceMeshFastBEM,forceMeshFastBEMfine,M_FastBEM,M_FastBEMfine,...
    '/home/sh268/Documents/TFM-simulation/basisFunction500500E8000Pa.mat',...
    '/home/sh268/Documents/TFM-simulation/basisFunction250250E8000PaFine.mat');

%for desktop
[pSRn5g100,pSRerrn5g100,regParamsn5g100] = calculateForceFineMeshImgScaled_fn(2,'groupForce',5/100,...
    '/home/sh268/Documents/Traction Force/Calibration/n5g',[],[],[],[],...
    '/home/sh268/orchestra/home/Documents/TFM-simulation/basisFunction500500E8000Pa.mat',...
    '/home/sh268/orchestra/home/Documents/TFM-simulation/basisFunction250250E8000PaFine.mat');
