[meanfMR,SEMfMR,regParams] = compareFTTC_BEM_FastBEM_fn('groupForce',3/100,...
'/home/sh268/orchestra/home/Documents/TFM-simulation/n3g',forceMesh,forceMeshFastBEM,M,M_FastBEM,...
'/home/sh268/orchestra/home/Documents/TFM-simulation/basisFunction5050.mat');
% n3g means noise= 3 percent and g = groupForce
[meanfMRn5g,SEMfMRn5g,regParamsn5g] = compareFTTC_BEM_FastBEM_fn('groupForce',5/100,...
'/home/sh268/orchestra/home/Documents/TFM-simulation/n5g',forceMesh,forceMeshFastBEM,M,M_FastBEM,...
'/home/sh268/orchestra/home/Documents/TFM-simulation/basisFunction5050.mat');
% n1s means noise= 1 percent and g = groupForce

% For making new M and M_FastBEM
[meanfMRn1g,SEMfMRn1g,regParamsn1g] = compareFTTC_BEM_FastBEM_fn('groupForce',5/100,...
'/home/sh268/orchestra/home/Documents/TFM-simulation/n1g',forceMesh,forceMeshFastBEM,[],[],...
'/home/sh268/orchestra/home/Documents/TFM-simulation/basisFunction5050E10kPa.mat');
