%cellXploreMan(data, varargin) interactive display of movies via 2D DR plot.
%
% Inputs:
% 		  data:	cell array containing the cell DR coordinates, labels, 
%			% and movie paths as well as other metadata.
%
% Outputs:  		Can manually save snapshots of plots/annotations
%
%
% Andrew R. Jamieson, Dec. 2016


function cellXploreDR(data, varargin)


ip = inputParser;
ip.KeepUnmatched = true;
ip.CaseSensitive = false;
ip.addRequired('data', @isstruct);
ip.parse(data, varargin{:});
handles.data = data;


x = data.DR; 

%===============================================================================
% Setup main GUI window/figure
%===============================================================================

% bgColor = get(0,'defaultUicontrolBackgroundColor');
% hfig = figure('Units', 'normalized', 'Position', [0.05 0.5 0.5 0.5],...
%     'PaperPositionMode', 'auto', 'Toolbar', 'figure',...
%     'Color', bgColor,...
%     'DefaultUicontrolUnits', 'pixels', 'Units', 'pixels', 'Name', ... 
%     'DRworld');
% 
% pos = get(hfig, 'Position'); % [pixels];

h1 = figure(...
'Units','characters', 'Position',[135.8 45.2 97.9 39.2],...
'Visible',get(0,'defaultfigureVisible'),...
'Color',get(0,'defaultfigureColor'),...
'CurrentAxesMode','manual',...
'IntegerHandle','off',...
'MenuBar','none',...
'Name','cellXplore',...
'NumberTitle','off',...
'Tag','figure1',...
'Resize','off',...
'PaperPosition',get(0,'defaultfigurePaperPosition'),...
'ScreenPixelsPerInchMode','manual',...
'HandleVisibility','callback');


h12 = uicontrol(...
'Parent',h1,...
'FontUnits','pixels',...
'Units','characters',...
'HorizontalAlignment','left',...
'String','Cell Explorer',...
'Style','text',...
'Position',[3 36 59 2],...
'Children',[],...
'Tag','text2',...
'FontSize',18,...
'FontWeight','bold');

%-------------------------------------------------------------------------------
% Control/Movie panels of GUI
%-------------------------------------------------------------------------------

h2_DR = uipanel('Parent',h1, 'FontUnits','pixels', 'Units','pixels',...
'Title','2D Visualization - Dimension Reduction','Tag','uipanel_axes',...
'Position',[49 224.07 358 354],'FontSize',13,'FontSizeMode',...
get(0,'defaultuipanelFontSizeMode'));

h_movie = uipanel(...
'Parent',h1,'FontUnits','pixels','Units','pixels','Title','Cell Movie',...
'Tag','uipanel_video','Position',[408 377 289 202],...
'FontSize',13,'FontSizeMode',get(0,'defaultuipanelFontSizeMode'));

h9 = uipanel('Parent',h1,'FontUnits','pixels','Units','pixels',...
'Title','Cell Labeling','Tag','uipanel_annotate','Position',[410 77 284 293],...
'FontSize',13,'FontSizeMode',get(0,'defaultuipanelFontSizeMode'));

h10 = uipanel('Parent',h1,'FontUnits','pixels','Units','pixels',...
'Title','Data Selection Criterion','Tag','uipanel_select',...
'Position',[46 75 359 152],'FontSize',13,'FontSizeMode',...
get(0,'defaultuipanelFontSizeMode'));

%===============================================================================
% Set up track display
%===============================================================================
nf = 10; % number of frames
fidx = 1; % current frame
handles.frameSlider = uicontrol(h_movie, 'Style', 'slider', 'Units', 'pixels',...
        'Value', fidx, 'Min', 1, 'Max', nf,'SliderStep', [1/(nf-1) 0.5], ...
        'Position',[0 3 286 20]);%,'Callback', @frameSliderRelease_Callback);

%===============================================================================
% Set up DR viz axes
%===============================================================================

opts = {'Parent', h2_DR, 'Units', 'pixels', 'Position', [20 20 320 300]};
h3 = axes(opts{:});

% haxes = axes('Position', [5 5 100 100], 'Parent', h2);

% PCA
% set(haxes, 'Visible', 'on')
scatter(h3, x(1,:), x(2,:), 14, x(3,:));

set(h3, 'XLim', [0 100]);
set(h3, 'Title', title('Hello'));

% tSNE
% scatter(haxes, x(2,:), x(4,:), 14, x(3,:));



