evaluationStartTime = clock;
            disp(sprintf(...
                '\n\nexperiment %i: track tags for ''%s''. Start at %s',...
                iExperiment,...
                experiment(iExperiment).projectName,...
                datestr(evaluationStartTime)));

            % track tags
            [idlisttrack,debugData] = ...
                tagTracker({ fullfile(...
                experiment(iExperiment).movieDir,...
                experiment(iExperiment).rawMovieName),...
                'corr/raw'},experiment(iExperiment).idlist_L,...
                experiment(iExperiment).dataProperties,...
                1,struct('fStats',1));


            % store and save
            experiment(iExperiment).trackerFStats = debugData.fStats;
            experiment(iExperiment).idlisttrack = idlisttrack;
            save(fullfile(experiment(iExperiment).movieDir,...
                experiment(iExperiment).idlist_LName),'idlist_L');

            % update status
            experiment(iExperiment).status = 6;
            % display elapsed time
            disp(sprintf('time elapsed: %i s',...
                round(etime(clock,evaluationStartTime))))