% %% Resume training a network
clc;
clear;
[filename, pathname] = uigetfile('*.mat','Which file to resume from layers checkpoint?',...
                        '/work/bioinformatics/shared/dope/torch/test/217x217/');
load(fullfile(pathname,filename));

[filename, pathname] = uigetfile('*.mat','Which training set to use?',...
                       '/work/bioinformatics/shared/dope/torch/test/217x217/');
load(fullfile(pathname,filename));

%% Define new Checkpoint
[checkPointDir] = uigetdir('/work/bioinformatics/shared/dope/torch/test/217x217/',...
                            'Where to store net Checkpoints?');

if ~verLessThan('matlab', '9.3')

    options = trainingOptions('sgdm',...
        'MaxEpochs',10000, ...
        'ValidationFrequency',5000,...
        'MiniBatchSize',50,...
        'Verbose',true,...
        'Plots','training-progress',...
        'ValidationData',imdsValid,...
        'ValidationPatience', Inf,...,
        'ExecutionEnvironment' , 'multi-gpu',...
        'CheckpointPath',checkPointDir);%fullfile(dataRootDir,'netTEMP'));
 
end


trainedNet = trainNetwork(imdsTrain,net.Layers,options);
