%Generated by Philippe Roudot to remove the dark pixels introduced by the
%light-sheet mode operation of the Hamamatsu Flash 4.0 Cameras.  Used on
%clathrin-mediated endocytosis tracking for Biophys J. paper, 2015.


vol=MD.getChannel(1).loadStack(1);
residue=(sum(vol,3)-medfilt2(sum(vol,3),[3 3]));
sig=sqrt(var(residue(:)))
thresh=median(residue(:))-3*sig
indx=residue<thresh;
filterVol=vol;
for z=1:size(vol,3) slice=vol(:,:,z); f=medfilt2(slice,[3 3]); slice(indx)=f(indx);filterVol(:,:,z)=slice; end
stackWrite(filterVol,'filterT1.tif')
