function fourScript()
scriptDeskewLatticeData
movieSelectorGUI
createMovieManagementFile
loadMoviesManagementFile
scriptEB3DetectAndTracking
scriptKinetochoreTracking
scriptAnalyseResults
scriptCroppingMovie