# Amira Project 600
# Amira
# Generated by Amira 6.0.0
remove -all
remove "physics.icol" "volrenRed.col" "time-0001.tif" "pointSourceAutoSigmaLM.am_t_0001.am" "Volren" "Spatial Graph View" "Time Series Control" "Time Series Control 2"

# Create viewers
viewer setVertical 1

viewer 0 setTransparencyType 6
viewer 0 setAutoRedraw 0
viewer 0 show
viewer 1 setTransparencyType 6
viewer 1 setAutoRedraw 0
viewer 1 show
mainWindow show

set hideNewModules 1
[ load ${AMIRA_ROOT}/data/colormaps/physics.icol ] setLabel "physics.icol"
"physics.icol" setIconPosition 0 0
"physics.icol" setNoRemoveAll 1
"physics.icol" master disconnect
"physics.icol" Datafield disconnect
"physics.icol" fire
"physics.icol" setMinMax 0 1
"physics.icol" flags setValue 1
"physics.icol" shift setMinMax -1 1
"physics.icol" shift setButtons 0
"physics.icol" shift setEditButton 1
"physics.icol" shift setIncrement 0.133333
"physics.icol" shift setValue 0
"physics.icol" shift setSubMinMax -1 1
"physics.icol" scale setMinMax 0 1
"physics.icol" scale setButtons 0
"physics.icol" scale setEditButton 1
"physics.icol" scale setIncrement 0.1
"physics.icol" scale setValue 1
"physics.icol" scale setSubMinMax 0 1
"physics.icol" fire
"physics.icol" setViewerMask 16383

set hideNewModules 1
[ load ${AMIRA_ROOT}/data/colormaps/volrenRed.col ] setLabel "volrenRed.col"
"volrenRed.col" setIconPosition 0 0
"volrenRed.col" setNoRemoveAll 1
"volrenRed.col" setVar "CustomHelp" {HxColormap256}
"volrenRed.col" master disconnect
"volrenRed.col" Datafield disconnect
"volrenRed.col" fire
"volrenRed.col" setMinMax 10 180
"volrenRed.col" flags setValue 1
"volrenRed.col" shift setMinMax -1 1
"volrenRed.col" shift setButtons 0
"volrenRed.col" shift setEditButton 1
"volrenRed.col" shift setIncrement 0.133333
"volrenRed.col" shift setValue 0
"volrenRed.col" shift setSubMinMax -1 1
"volrenRed.col" scale setMinMax 0 1
"volrenRed.col" scale setButtons 0
"volrenRed.col" scale setEditButton 1
"volrenRed.col" scale setIncrement 0.1
"volrenRed.col" scale setValue 1
"volrenRed.col" scale setSubMinMax 0 1
"volrenRed.col" fire
"volrenRed.col" setViewerMask 16383

set hideNewModules 0
create HxDynamicFileSeriesCtrl "Time Series Control"
"Time Series Control" setIconPosition -12 65
"Time Series Control" init -loadCmd {load -tif +mode 100 +box 0 27900 0 23800 0 28556 "$FILENAME"} \
"/work/gdanuser/proudot/project/EB3-3D-track/packaging/alpha/plusTipTracker3D-alpha-1/data/A1_HeLa_Cells_EB1/anaphase/Cell1/ch0/time-0001.tif" \
"/work/gdanuser/proudot/project/EB3-3D-track/packaging/alpha/plusTipTracker3D-alpha-1/data/A1_HeLa_Cells_EB1/anaphase/Cell1/ch0/time-0002.tif" \
"/work/gdanuser/proudot/project/EB3-3D-track/packaging/alpha/plusTipTracker3D-alpha-1/data/A1_HeLa_Cells_EB1/anaphase/Cell1/ch0/time-0003.tif" \
"/work/gdanuser/proudot/project/EB3-3D-track/packaging/alpha/plusTipTracker3D-alpha-1/data/A1_HeLa_Cells_EB1/anaphase/Cell1/ch0/time-0004.tif" \
"/work/gdanuser/proudot/project/EB3-3D-track/packaging/alpha/plusTipTracker3D-alpha-1/data/A1_HeLa_Cells_EB1/anaphase/Cell1/ch0/time-0005.tif" \
"/work/gdanuser/proudot/project/EB3-3D-track/packaging/alpha/plusTipTracker3D-alpha-1/data/A1_HeLa_Cells_EB1/anaphase/Cell1/ch0/time-0006.tif" \
"/work/gdanuser/proudot/project/EB3-3D-track/packaging/alpha/plusTipTracker3D-alpha-1/data/A1_HeLa_Cells_EB1/anaphase/Cell1/ch0/time-0007.tif" \
"/work/gdanuser/proudot/project/EB3-3D-track/packaging/alpha/plusTipTracker3D-alpha-1/data/A1_HeLa_Cells_EB1/anaphase/Cell1/ch0/time-0008.tif" \
"/work/gdanuser/proudot/project/EB3-3D-track/packaging/alpha/plusTipTracker3D-alpha-1/data/A1_HeLa_Cells_EB1/anaphase/Cell1/ch0/time-0009.tif"
"Time Series Control" cachedSteps setMinMax 0 0 9
"Time Series Control" cachedSteps setValue 0 9
"Time Series Control" options setValue 0 0
"Time Series Control" options setToggleVisible 0 1
"Time Series Control" options setValue 1 0
"Time Series Control" options setToggleVisible 1 1
"Time Series Control" options setValue 2 0
"Time Series Control" options setToggleVisible 2 1
"Time Series Control" options setValue 3 0
"Time Series Control" options setToggleVisible 3 1
"Time Series Control" fire
"Time Series Control" time disconnect
"Time Series Control" time setMinMax 0 8
"Time Series Control" time setSubMinMax 0 8
"Time Series Control" time setValue 0
"Time Series Control" time setDiscrete 1
"Time Series Control" time setIncrement 1
"Time Series Control" time animationMode -once
"Time Series Control" applyTransformToResult 1
"Time Series Control" fire
"Time Series Control" setViewerMask 16383
"Time Series Control" setPickable 1

set hideNewModules 0
[ load -tif +mode 100 +box 0 27900 0 23800 0 28556 /work/gdanuser/proudot/project/EB3-3D-track/packaging/alpha/plusTipTracker3D-alpha-1/data/A1_HeLa_Cells_EB1/anaphase/Cell1/ch0/time-0001.tif ] setLabel "time-0001.tif"
"time-0001.tif" setIconPosition -69 10
"time-0001.tif" master connect "Time Series Control"
"time-0001.tif" sharedColormap setDefaultColor 0.8 0.8 0.8
"time-0001.tif" sharedColormap setDefaultAlpha 0.500000
"time-0001.tif" sharedColormap setLocalRange 1
"time-0001.tif" sharedColormap setLocalMinMax 0.000000 1.000000
"time-0001.tif" sharedColormap enableAlpha 1
"time-0001.tif" sharedColormap enableAlphaToggle 1
"time-0001.tif" sharedColormap setAutoAdjustRangeMode 1
"time-0001.tif" sharedColormap disconnect
"time-0001.tif" fire
"time-0001.tif" setViewerMask 16383

set hideNewModules 0
create HxVolren "Volren"
"Volren" setIconPosition 373 9
"Volren" setVar "CustomHelp" {HxVolren}
"Volren" data connect "time-0001.tif"
"Volren" Labels disconnect
"Volren" ROI disconnect
"Volren" roiCornerCut disconnect
"Volren" color0 setDefaultColor 0.137 0.941 0.089
"Volren" color0 setDefaultAlpha 0.500000
"Volren" color0 setLocalRange 1
"Volren" color0 setLocalMinMax -10.000000 490.000000
"Volren" color0 enableAlpha 1
"Volren" color0 enableAlphaToggle 1
"Volren" color0 setAutoAdjustRangeMode 1
"Volren" color0 setColorbarMinMax -10 1015
"Volren" color0 connect "volrenRed.col"
"Volren" fire
"Volren" tabs setValue 0
"Volren" options0 setState {}
"Volren" alphaScale0 setMinMax 0 1
"Volren" alphaScale0 setButtons 0
"Volren" alphaScale0 setEditButton 1
"Volren" alphaScale0 setIncrement 0.1
"Volren" alphaScale0 setValue 1
"Volren" alphaScale0 setSubMinMax 0 1
"Volren" commonMode setState {item 0 2 item 1 0 }
"Volren" commonOptions setValue 0 0
"Volren" commonOptions setToggleVisible 0 1
"Volren" commonDRRGamma setMinMax 0 10
"Volren" commonDRRGamma setButtons 0
"Volren" commonDRRGamma setEditButton 1
"Volren" commonDRRGamma setIncrement 0.666667
"Volren" commonDRRGamma setValue 1
"Volren" commonDRRGamma setSubMinMax 0 10
"Volren" shading setValue 0
"Volren" coefficients setState {item 0 0.3 item 1 0.6 item 2 0.7 color 666 1 1 1 }
"Volren" lightAngle setValue 0
"Volren" shadingLightAngleYaw setMinMax -1 1
"Volren" shadingLightAngleYaw setButtons 0
"Volren" shadingLightAngleYaw setEditButton 1
"Volren" shadingLightAngleYaw setIncrement 0.133333
"Volren" shadingLightAngleYaw setValue 0
"Volren" shadingLightAngleYaw setSubMinMax -1 1
"Volren" shadingLightAnglePitch setMinMax -0.5 0.5
"Volren" shadingLightAnglePitch setButtons 0
"Volren" shadingLightAnglePitch setEditButton 1
"Volren" shadingLightAnglePitch setIncrement 0.0666667
"Volren" shadingLightAnglePitch setValue 0
"Volren" shadingLightAnglePitch setSubMinMax -0.5 0.5
"Volren" sampleDistance setMinMax 0 10
"Volren" sampleDistance setButtons 0
"Volren" sampleDistance setEditButton 1
"Volren" sampleDistance setIncrement 0.666667
"Volren" sampleDistance setValue 0
"Volren" sampleDistance setSubMinMax 0 10
"Volren" defaultMaterial setState {item 0 1 item 1 0 color 2 1 1 1 item 3 0 item 4 0 }
"Volren" linkMaterialTransferFunction 256 0
"Volren" fire
"Volren" setViewerMask 16383
"Volren" setPickable 1

set hideNewModules 0
create HxDynamicFileSeriesCtrl "Time Series Control 2"
"Time Series Control 2" setIconPosition -28 91
"Time Series Control 2" init -loadCmd {load "$FILENAME"} \
"/work/gdanuser/proudot/project/EB3-3D-track/packaging/alpha/plusTipTracker3D-alpha-1/data/A1_HeLa_Cells_EB1/anaphase/Cell1/analysis/EB3/pointSourceAutoSigmaLM/amiraVertex/pointSourceAutoSigmaLM.am_t_0001.am" \
"/work/gdanuser/proudot/project/EB3-3D-track/packaging/alpha/plusTipTracker3D-alpha-1/data/A1_HeLa_Cells_EB1/anaphase/Cell1/analysis/EB3/pointSourceAutoSigmaLM/amiraVertex/pointSourceAutoSigmaLM.am_t_0002.am" \
"/work/gdanuser/proudot/project/EB3-3D-track/packaging/alpha/plusTipTracker3D-alpha-1/data/A1_HeLa_Cells_EB1/anaphase/Cell1/analysis/EB3/pointSourceAutoSigmaLM/amiraVertex/pointSourceAutoSigmaLM.am_t_0003.am" \
"/work/gdanuser/proudot/project/EB3-3D-track/packaging/alpha/plusTipTracker3D-alpha-1/data/A1_HeLa_Cells_EB1/anaphase/Cell1/analysis/EB3/pointSourceAutoSigmaLM/amiraVertex/pointSourceAutoSigmaLM.am_t_0004.am" \
"/work/gdanuser/proudot/project/EB3-3D-track/packaging/alpha/plusTipTracker3D-alpha-1/data/A1_HeLa_Cells_EB1/anaphase/Cell1/analysis/EB3/pointSourceAutoSigmaLM/amiraVertex/pointSourceAutoSigmaLM.am_t_0005.am" \
"/work/gdanuser/proudot/project/EB3-3D-track/packaging/alpha/plusTipTracker3D-alpha-1/data/A1_HeLa_Cells_EB1/anaphase/Cell1/analysis/EB3/pointSourceAutoSigmaLM/amiraVertex/pointSourceAutoSigmaLM.am_t_0006.am" \
"/work/gdanuser/proudot/project/EB3-3D-track/packaging/alpha/plusTipTracker3D-alpha-1/data/A1_HeLa_Cells_EB1/anaphase/Cell1/analysis/EB3/pointSourceAutoSigmaLM/amiraVertex/pointSourceAutoSigmaLM.am_t_0007.am" \
"/work/gdanuser/proudot/project/EB3-3D-track/packaging/alpha/plusTipTracker3D-alpha-1/data/A1_HeLa_Cells_EB1/anaphase/Cell1/analysis/EB3/pointSourceAutoSigmaLM/amiraVertex/pointSourceAutoSigmaLM.am_t_0008.am" \
"/work/gdanuser/proudot/project/EB3-3D-track/packaging/alpha/plusTipTracker3D-alpha-1/data/A1_HeLa_Cells_EB1/anaphase/Cell1/analysis/EB3/pointSourceAutoSigmaLM/amiraVertex/pointSourceAutoSigmaLM.am_t_0009.am"
"Time Series Control 2" cachedSteps setMinMax 0 0 9
"Time Series Control 2" cachedSteps setValue 0 9
"Time Series Control 2" options setValue 0 0
"Time Series Control 2" options setToggleVisible 0 1
"Time Series Control 2" options setValue 1 0
"Time Series Control 2" options setToggleVisible 1 1
"Time Series Control 2" options setValue 2 0
"Time Series Control 2" options setToggleVisible 2 1
"Time Series Control 2" options setValue 3 0
"Time Series Control 2" options setToggleVisible 3 1
"Time Series Control 2" fire
"Time Series Control 2" time connect "Time Series Control"
"Time Series Control 2" time setMinMax 0 8
"Time Series Control 2" time setSubMinMax 0 8
"Time Series Control 2" time setValue 0
"Time Series Control 2" time setDiscrete 1
"Time Series Control 2" time setIncrement 1
"Time Series Control 2" time animationMode -once
"Time Series Control 2" applyTransformToResult 1
"Time Series Control 2" fire
"Time Series Control 2" setViewerMask 16383
"Time Series Control 2" select
"Time Series Control 2" setPickable 1

set hideNewModules 0
[ load /work/gdanuser/proudot/project/EB3-3D-track/packaging/alpha/plusTipTracker3D-alpha-1/data/A1_HeLa_Cells_EB1/anaphase/Cell1/analysis/EB3/pointSourceAutoSigmaLM/amiraVertex/pointSourceAutoSigmaLM.am_t_0001.am ] setLabel "pointSourceAutoSigmaLM.am_t_0001.am"
"pointSourceAutoSigmaLM.am_t_0001.am" setIconPosition -97 130
"pointSourceAutoSigmaLM.am_t_0001.am" master connect "Time Series Control 2"
"pointSourceAutoSigmaLM.am_t_0001.am" fire
"pointSourceAutoSigmaLM.am_t_0001.am" fire
"pointSourceAutoSigmaLM.am_t_0001.am" setViewerMask 16383

set hideNewModules 0
create HxSpatialGraphView "Spatial Graph View"
"Spatial Graph View" setIconPosition 298 135
"Spatial Graph View" setVar "CustomHelp" {HxSpatialGraphView}
"Spatial Graph View" data connect "pointSourceAutoSigmaLM.am_t_0001.am"
"Spatial Graph View" Statistics disconnect
"Spatial Graph View" nodeColormap setDefaultColor 1 0.8 0.5
"Spatial Graph View" nodeColormap setDefaultAlpha 0.500000
"Spatial Graph View" nodeColormap setLocalRange 1
"Spatial Graph View" nodeColormap setLocalMinMax 0.000000 1.000000
"Spatial Graph View" nodeColormap enableAlpha 1
"Spatial Graph View" nodeColormap enableAlphaToggle 1
"Spatial Graph View" nodeColormap setAutoAdjustRangeMode 1
"Spatial Graph View" nodeColormap setColorbarMinMax 0 1
"Spatial Graph View" nodeColormap connect "physics.icol"
"Spatial Graph View" segmentColormap setDefaultColor 1 0.8 0.5
"Spatial Graph View" segmentColormap setDefaultAlpha 0.500000
"Spatial Graph View" segmentColormap setLocalRange 1
"Spatial Graph View" segmentColormap setLocalMinMax 0.000000 1.000000
"Spatial Graph View" segmentColormap enableAlpha 1
"Spatial Graph View" segmentColormap enableAlphaToggle 1
"Spatial Graph View" segmentColormap setAutoAdjustRangeMode 1
"Spatial Graph View" segmentColormap setColorbarMinMax 0 1
"Spatial Graph View" segmentColormap connect "physics.icol"
"Spatial Graph View" fire
"Spatial Graph View" itemsToShow setValue 0 1
"Spatial Graph View" itemsToShow setToggleVisible 0 1
"Spatial Graph View" itemsToShow setValue 1 0
"Spatial Graph View" itemsToShow setToggleVisible 1 1
"Spatial Graph View" nodeScale setIndex 0 0
"Spatial Graph View" nodeScaleFactor setMinMax 0 2514.5
"Spatial Graph View" nodeScaleFactor setButtons 0
"Spatial Graph View" nodeScaleFactor setEditButton 1
"Spatial Graph View" nodeScaleFactor setIncrement 167.633
"Spatial Graph View" nodeScaleFactor setValue 112.111
"Spatial Graph View" nodeScaleFactor setSubMinMax 0 2514.5
"Spatial Graph View" nodeColoring setIndex 0 0
"Spatial Graph View" nodeLabelColoringOptions setValue 0
"Spatial Graph View" nodeColor setColor 0 0.8 0.405797 0.405797
"Spatial Graph View" segmentStyle setValue 0 1
"Spatial Graph View" segmentStyle setToggleVisible 0 1
"Spatial Graph View" segmentStyle setValue 1 0
"Spatial Graph View" segmentStyle setToggleVisible 1 1
"Spatial Graph View" segmentStyle setValue 2 0
"Spatial Graph View" segmentStyle setToggleVisible 2 1
"Spatial Graph View" tubeScale setIndex 0 0
"Spatial Graph View" tubeScaleFactor setMinMax 0 2514.5
"Spatial Graph View" tubeScaleFactor setButtons 0
"Spatial Graph View" tubeScaleFactor setEditButton 1
"Spatial Graph View" tubeScaleFactor setIncrement 167.633
"Spatial Graph View" tubeScaleFactor setValue 125.725
"Spatial Graph View" tubeScaleFactor setSubMinMax 0 2514.5
"Spatial Graph View" segmentWidth setMinMax 0 10
"Spatial Graph View" segmentWidth setButtons 0
"Spatial Graph View" segmentWidth setEditButton 1
"Spatial Graph View" segmentWidth setIncrement 0.666667
"Spatial Graph View" segmentWidth setValue 1
"Spatial Graph View" segmentWidth setSubMinMax 0 10
"Spatial Graph View" segmentColoring setIndex 0 0
"Spatial Graph View" segmentLabelColoringOptions setValue 0
"Spatial Graph View" segmentColor setColor 0 0.8 0.8 0.8
"Spatial Graph View" pointSize setMinMax 0 15
"Spatial Graph View" pointSize setButtons 0
"Spatial Graph View" pointSize setEditButton 1
"Spatial Graph View" pointSize setIncrement 1
"Spatial Graph View" pointSize setValue 4
"Spatial Graph View" pointSize setSubMinMax 0 15
"Spatial Graph View" setVisibility HIJMPLPPPPPPHPAAAJPKADPN HIJMPLPPHPGIAAAAEAGNKHFJ
"Spatial Graph View" fire
"Spatial Graph View" setViewerMask 16382
"Spatial Graph View" setPickable 1

set hideNewModules 0

viewer 0 setCameraOrientation -0.600581 0.6593 0.452356 2.62299
viewer 0 setCameraPosition 11014.4 16629.3 11404.2
viewer 0 setCameraFocalDistance 11453
viewer 0 setCameraNearDistance -13680.5
viewer 0 setCameraFarDistance 25635
viewer 0 setCameraType orthographic
viewer 0 setCameraHeight 26923.5
viewer 0 setAutoRedraw 1
viewer 0 redraw

viewer 1 setCameraOrientation -0.600581 0.6593 0.452356 2.62299
viewer 1 setCameraPosition 11014.4 16629.3 11404.2
viewer 1 setCameraFocalDistance 11453
viewer 1 setCameraNearDistance -13680.5
viewer 1 setCameraFarDistance 25635
viewer 1 setCameraType orthographic
viewer 1 setCameraHeight 26923.5
viewer 1 linkViewer 0
viewer 1 setAutoRedraw 1
viewer 1 redraw

theObjectPool setSelectionOrder {Time Series Control 2}
