[windowDistFromEdgeAlphaVY773AComb,sptPropInWindowAlphaVY773AComb0,...
    sptPropInWindowAlphaVY773ACombModDiff,sptPropInWindowAlphaVY773ACombModRatio,...
    sptPropInWindowAlphaVY773ACombModDiffRatio,sptPropActivityOnsetAlphaVY773A] = ...
    sptRelToActivityMultipleCells(sptPropInWindowAlphaVY773AInd,windowDistFromEdgeAlphaVY773AInd,5);