condName = {'AlphaV','AlphaV717Trunc','AlphaV724Trunc','Talin','Farn','Lifeact'};
numMode = 4;
minNP = 4;

for iType = 1
    
    windowDistFromEdge = [];
    for iCond =1 : length(condName)
        eval(['windowDistFromEdge = [windowDistFromEdge; windowDistFromEdge' condName{iCond} 'Comb(iType)];'])
    end
    
    %particle density
    sptPropInWindow = [];
    for iCond = 1 : length(condName)
        eval(['sptPropInWindow = [sptPropInWindow;' ...
            'sptPropInWindow' condName{iCond} 'CombModRatio(iType).directAll.densityParticles];'])
    end
    plotSptRelToActivityOnsetAdaptiveWindowsV2Multi(sptPropInWindow,...
        windowDistFromEdge,1,minNP,['Particle density overall, protType ' num2str(iType)],...
        ['DensityOverall_protType' num2str(iType) '.fig'],[0.111 10 1/(0.111^2)],...
        'Molecule density (per um^2)',[-100 150 0 11],0,[],[],condName);
    
    %overall diffusion coefficient
    sptPropInWindow = [];
    for iCond = 1 : length(condName)
        eval(['sptPropInWindow = [sptPropInWindow;' ...
            'sptPropInWindow' condName{iCond} 'CombModRatio(iType).diffModeAnalysis.diffCoefModeAll];'])
    end
    plotSptRelToActivityOnsetAdaptiveWindowsV2Multi(sptPropInWindow,...
        windowDistFromEdge,1,minNP,['Diffusion coefficient overall, protType ' num2str(iType)],...
        ['DiffCoefOverall_protType' num2str(iType) '.fig'],[0.111 10 (0.111^2)/0.025],...
        'Diffusion coefficient (um^2/s)',[-100 150 0.085 0.65],0,[],[],condName);
    
    %fraction in each diffusion mode
    sptPropInWindow = [];
    for iCond = 1 : length(condName)
        eval(['sptPropInWindow = [sptPropInWindow;' ...
            'sptPropInWindow' condName{iCond} 'CombModRatio(iType).diffModeAnalysis.fracModeClass];'])
    end
    for iMode = 1 : 2
        plotSptRelToActivityOnsetAdaptiveWindowsV2Multi(sptPropInWindow,...
            windowDistFromEdge,iMode,minNP,['Fraction Mode ' num2str(iMode) ', protType ' num2str(iType)],...
            ['FractionMode' num2str(iMode) '_protType' num2str(iType) '.fig'],[0.111 10 1],...
            ['Fraction Mode ' num2str(iMode)],[-100 150 0 1],0,[],[],condName);
    end
    for iMode = 3 : numMode
        plotSptRelToActivityOnsetAdaptiveWindowsV2Multi(sptPropInWindow(1:end-1),...
            windowDistFromEdge(1:end-1),iMode,minNP,['Fraction Mode ' num2str(iMode) ', protType ' num2str(iType)],...
            ['FractionMode' num2str(iMode) '_protType' num2str(iType) '.fig'],[0.111 10 1],...
            ['Fraction Mode ' num2str(iMode)],[-100 150 0 1],0,[],[],condName(1:end-1));
    end
    
    %density of each diffusion mode
    sptPropInWindow = [];
    for iCond = 1 : length(condName)
        eval(['sptPropInWindow = [sptPropInWindow;' ...
            'sptPropInWindow' condName{iCond} 'CombModRatio(iType).diffModeAnalysis.densityModeClass];'])
    end
    for iMode = 1 : 2
        plotSptRelToActivityOnsetAdaptiveWindowsV2Multi(sptPropInWindow,...
            windowDistFromEdge,iMode,minNP,['Density Modes '  num2str(iMode) ', protType ' num2str(iType)],...
            ['DensityMode' num2str(iMode) '_protType' num2str(iType) '.fig'],[0.111 10  1/(0.111^2)],...
            ['Density Mode' num2str(iMode) ' (per um^2)'],[-100 150 0 11],0,[],[],condName);
    end
    for iMode = 3 : numMode
        plotSptRelToActivityOnsetAdaptiveWindowsV2Multi(sptPropInWindow(1:end-1),...
            windowDistFromEdge(1:end-1),iMode,minNP,['Density Modes '  num2str(iMode) ', protType ' num2str(iType)],...
            ['DensityMode' num2str(iMode) '_protType' num2str(iType) '.fig'],[0.111 10 1/(0.111^2)],...
            ['Density Mode' num2str(iMode) ' (per um^2)'],[-100 150 0 11],0,[],[],condName(1:end-1));
    end
    
end