function out = iatGUI_PD_data
%this file contains the menu items for the PD-menus in imarisAnalyzeTracksGUI

%itemname.......................number of tracks required.................case# in calcPlotData............
out = {'NONE', 					                0, 		        0,                    1,                -1;...
'===============================================',-1,           -1,                   1,                -1;...
'distance to origin',                           1, 		        0,                    2,                0;...
'distance between tracks',                      2, 		        0,                    3,                0;...
'-----------------------------------------------',-1,           -1,                   1,                -1;...
'displacement (along track)', 			        1, 		        0,                    4,               0;...
'displacement (relative to track)',             2,              0,                    5,               0;...
'===============================================',-1,           -1,                   1,                -1;...
'MSQD relative to origin',			            1, 		        0,                    6,               0;...
'MSQD relative to track',			            2, 		        0,                    7,               0;...
'MSQD relative to track, 1D',                   2, 		        0,                    8,               0;...
};
