createCodePackage('InvivoCytometer.m', ...
                  'additionalMatlabFiles', {'performCellCycleAnalysis.m', ...
                                            'batchCellCycleAnalysis.m'}, ...
                  'additionalNonMatlabFiles', {'weka.jar', 'libsvm.jar', ...
                                               'bioformats_package.jar', ... 
                                               'ANNlib.dll', 'libANNlib.dylib', 'libANNlib.so', 'ITKCommon.dll', ...
                                               'elastix.exe', 'transformix.exe', ...
                                               'elastixLinux', 'elastixMac', ...
                                               'elastixLinuxExec', 'elastixMacExec', ...
                                               'transformixLinux', 'transformixMac', ...
                                               'transformixLinuxExec', 'transformixMacExec', ...
                                               'elastixParamFile_rigid3D.txt'} ...
                 );   
                    