function pdemodel
[pde_fig,ax]=pdeinit;
pdetool('appl_cb',3);
set(ax,'DataAspectRatio',[1 1 1]);
set(ax,'PlotBoxAspectRatio',[1.5 1 1]);
set(ax,'XLim',[-1.5 1.5]);
set(ax,'YLim',[-1 1]);
set(ax,'XTickMode','auto');
set(ax,'YTickMode','auto');

% Geometry description:
pdeellip(-0.0009765625,-0.0009765625,1.1074218750000009,0.10156250000000022,...
0,'E1');
set(findobj(get(pde_fig,'Children'),'Tag','PDEEval'),'String','E1')

% Boundary conditions:
pdetool('changemode',0)
pdesetbd(4,...
'dir',...
2,...
str2mat('1','0','0','1'),...
str2mat('0','0'))
pdesetbd(3,...
'dir',...
2,...
str2mat('1','0','0','1'),...
str2mat('0','0'))
pdesetbd(2,...
'dir',...
2,...
str2mat('1','0','0','1'),...
str2mat('0','0'))
pdesetbd(1,...
'dir',...
2,...
str2mat('1','0','0','1'),...
str2mat('0','0'))

% Mesh generation:
setappdata(pde_fig,'Hgrad',1.3);
setappdata(pde_fig,'refinemethod','regular');
setappdata(pde_fig,'jiggle',char('on','mean',''));
pdetool('initmesh')
pdetool('refine')
pdetool('refine')

% PDE coefficients:
pdeseteq(1,...
str2mat('2*((gfun_youngs_mod(x,y))./(2*(1+(gfun_poisson_ratio))))+(2*((gfun_youngs_mod(x,y))./(2*(1+(gfun_poisson_ratio)))).*(gfun_poisson_ratio)./(1-(gfun_poisson_ratio)))','0','(gfun_youngs_mod(x,y))./(2*(1+(gfun_poisson_ratio)))','0','(gfun_youngs_mod(x,y))./(2*(1+(gfun_poisson_ratio)))','2*((gfun_youngs_mod(x,y))./(2*(1+(gfun_poisson_ratio)))).*(gfun_poisson_ratio)./(1-(gfun_poisson_ratio))','0','(gfun_youngs_mod(x,y))./(2*(1+(gfun_poisson_ratio)))','0','2*((gfun_youngs_mod(x,y))./(2*(1+(gfun_poisson_ratio))))+(2*((gfun_youngs_mod(x,y))./(2*(1+(gfun_poisson_ratio)))).*(gfun_poisson_ratio)./(1-(gfun_poisson_ratio)))'),...
str2mat('0.0','0.0','0.0','0.0'),...
str2mat('gfun_vol_f_xcomp(x,y)','gfun_vol_f_ycomp(x,y)'),...
str2mat('0','0','0','0'),...
'0:10',...
'0.0',...
'0.0',...
'[0 100]')
setappdata(pde_fig,'currparam',...
['gfun_youngs_mod(x,y) ';...
'gfun_poisson_ratio   ';...
'gfun_vol_f_xcomp(x,y)';...
'gfun_vol_f_ycomp(x,y)';...
'0                    '])

% Solve parameters:
setappdata(pde_fig,'solveparam',...
str2mat('0','1000','10','pdeadworst',...
'0.5','longest','0','1E-4','','fixed','Inf'))

% Plotflags and user data strings:
setappdata(pde_fig,'plotflags',[1 1 1 1 1 1 1 1 0 0 0 1 1 0 0 0 0 1]);
setappdata(pde_fig,'colstring','');
setappdata(pde_fig,'arrowstring','');
setappdata(pde_fig,'deformstring','');
setappdata(pde_fig,'heightstring','');
