function roi(obj)

p = obj.data.roiPosition;
s = obj.data.roiSize;

rectanglePointsStart = [...
    p;...
    p;...
    p+[s(1) 0 0];...
    p+[0 s(2) 0];...
    ];

rectanglePointsEnd = [...
    p+[s(1) 0 0];...
    p+[0 s(2) 0];...
    p+[s(1) s(2) 0];...
    p+[s(1) s(2) 0];...
    ];

rectangleLinkPointsStart = [...
    p;...
    p+[s(1) 0 0];...
    p+[0 s(2) 0];...
    p+[s(1) s(2) 0];...
    ];

rectangleLinkPointsEnd = [...
    p+[0 0 s(3)];...
    p+[s(1) 0 s(3)];...
    p+[0 s(2) s(3)];...
    p+[s(1) s(2) s(3)];...
    ];

roiPointsStart = [rectanglePointsStart;rectanglePointsStart+repmat([0 0 s(3)],4,1);rectangleLinkPointsStart];
roiPointsEnd = [rectanglePointsEnd;rectanglePointsEnd+repmat([0 0 s(3)],4,1);rectangleLinkPointsEnd];

obj.imaris.displaySegments(roiPointsStart,roiPointsEnd,'Display: ROI');

end

