function [intTypes intNames] = getIntTypeFields
%[intTypes intNames] = getIntTypeFields

intTypes = {'intForCurvSampMean',...
            'intForCurvSampSTD',...
            'intForCurvSampMin',...
            'intForCurvSampMax',...
            'intForCurvSampMeanDepthNorm',...
            'intForCurvSampSTDDepthNorm',...
            'intForCurvSampMinDepthNorm',...
            'intForCurvSampMaxDepthNorm'};
        
%Intuitive names        
intNames = {'Mean Intensity',...
            'STD Intensity',...
            'Min Intensity',...
            'Max Intensity',...
            'Depth Normalized Mean Intensity',...
            'Depth Normalized STD Intensity',...
            'Depth Normalized Min Intensity',...
            'Depth Normalized Max Intensity'};        