function valid_feature_index = find_valid_feature_index(output_feature,feature_index)
 
valid_feature_index = feature_index;
 
 if(isempty(output_feature.straightness_per_filament_pool))
     valid_feature_index(1)=0;
 end
 
 if(isempty(output_feature.length_per_filament_pool))
     valid_feature_index(2)=0;
 end
  if(isempty(output_feature.pixel_number_per_filament_pool))
     valid_feature_index(3)=0;
 end
  if(isempty(output_feature.density_filament))
     valid_feature_index(4)=0;
 end
  if(isempty(output_feature.scrabled_density_filament))
     valid_feature_index(5)=0;
 end
  if(isempty(output_feature.orientation_pixel_pool_display))
     valid_feature_index(6)=0;
 end
  if(isempty(output_feature.orientation_pixel_pool_display_center))
     valid_feature_index(7)=0;
 end
  if(isempty(output_feature.intensity_per_filament_pool))
     valid_feature_index(8)=0;
 end
  if(isempty(output_feature.mean_intensity_per_filament_pool))
     valid_feature_index(9)=0;
 end
 
  if(isempty(output_feature.intensity_per_fat_filament_pool))
     valid_feature_index(10)=0;
 end
  if(isempty(output_feature.mean_intensity_per_fat_filament_pool))
     valid_feature_index(11)=0;
 end
  if(isempty(output_feature.scale_per_filament_pool))
     valid_feature_index(12)=0;
 end
  if(isempty(output_feature.st_per_filament_pool))
     valid_feature_index(13)=0;
 end
  if(isempty(output_feature.mean_st_per_filament_pool))
     valid_feature_index(14)=0;
 end
  if(isempty(output_feature.st_per_fat_filament_pool))
     valid_feature_index(15)=0;
 end
  if(isempty(output_feature.mean_st_per_fat_filament_pool))
     valid_feature_index(16)=0;
 end
  if(isempty(output_feature.filament_mean_curvature))
     valid_feature_index(17)=0;
 end
  if(isempty(output_feature.curvature_per_pixel_pool))
     valid_feature_index(18)=0;
 end
  if(isempty(output_feature.nmssum_ratio_pool))
     valid_feature_index(19)=0;
 end
  if(isempty(output_feature.nmsmean_ratio_pool))
     valid_feature_index(20)=0;
 end
  if(isempty(output_feature.intsum_ratio_pool))
     valid_feature_index(21)=0;
 end
  if(isempty(output_feature.intmean_ratio_pool))
     valid_feature_index(22)=0;
 end
  if(isempty(output_feature.filasum_ratio_pool))
     valid_feature_index(23)=0;
 end
  if(isempty(output_feature.filamean_ratio_pool))
     valid_feature_index(24)=0;
  end
  if(isempty(output_feature.nmssum_ratio_pool_autoDpc))
     valid_feature_index(25)=0;
 end
  if(isempty(output_feature.nmsmean_ratio_pool_autoDpc))
     valid_feature_index(26)=0;
 end
  if(isempty(output_feature.intsum_ratio_pool_autoDpc))
     valid_feature_index(27)=0;
 end
  if(isempty(output_feature.intmean_ratio_pool_autoDpc))
     valid_feature_index(28)=0;
 end
  if(isempty(output_feature.filasum_ratio_pool_autoDpc))
     valid_feature_index(29)=0;
 end
 
  if(isempty(output_feature.filamean_ratio_pool_autoDpc))
     valid_feature_index(30)=0;
 end
  if(isempty(output_feature.Centripetal_fila))
     valid_feature_index(31)=0;
 end
  if(isempty(output_feature.Centripetal_pixel))
     valid_feature_index(32)=0;
 end
  if(isempty(output_feature.number_of_nucleus))
     valid_feature_index(33)=0;
 end
 
                                           
