[windowDistFromEdgeAlphaVY773ATmpComb,sptPropInWindowAlphaVY773ATmpComb0,...
    sptPropInWindowAlphaVY773ATmpCombModDiff,sptPropInWindowAlphaVY773ATmpCombModRatio,...
    sptPropInWindowAlphaVY773ATmpCombModDiffRatio,sptPropActivityOnsetAlphaVY773ATmp] = ...
    sptRelToActivityMultipleCells(sptPropInWindowAlphaVY773AInd(:,1:4),windowDistFromEdgeAlphaVY773AInd(:,1:4),5);