[windowDistFromEdgeBeta3Comb,sptPropInWindowBeta3Comb0,...
    sptPropInWindowBeta3CombModDiff,sptPropInWindowBeta3CombModRatio,...
    sptPropInWindowBeta3CombModDiffRatio,sptPropActivityOnsetBeta3] = ...
    sptRelToActivityMultipleCells(sptPropInWindowBeta3Ind,windowDistFromEdgeBeta3Ind,5);