function plate_network_feature_plotting(Identifier_thisML,...
    CFMP_feature_ordered_thisML,...
    CFMP_feature_thisML,...
    ChMP_feature_thisML,ChMP_feature_perwell_thisML)
nFrame = size(CFMP_feature_ordered_thisML{1}{1},3);
iChannel = 1;
nMovie = numel(ChMP_feature_thisML);

ChMP_feature_thisML_ch1 = nan(18,8,nMovie);

for iMD = 1 : numel(ChMP_feature_thisML)
    ChMP_feature_thisML_ch1(:,:,iMD) = ChMP_feature_thisML{iMD}{1}(:,:);
end

whole_plate_stat = median(ChMP_feature_thisML_ch1,3);
whole_plate_stat(1:18,1) = mean(ChMP_feature_thisML_ch1(:,1,:),3);


for iMD = 1 : nMovie
    for iW = 1 : nFrame/4
        for iF = 1:18
            for iS = 1 :8
                CFMP_feature_ordered_thisCh_perwell(iMD,iW,iF,iS) = ...
                    median(CFMP_feature_ordered_thisML{iMD}{1}(iF,iS,(iW-1)*4+1:(iW)*4));
            end
        end
    end
end


textcell = {'Straightness of filament (for each filament)',...
    'Length (for each filament)',...
    'Pixel number of segmentation (for each filament)',...
    'Filament density (for each valid pixel)',...
    'Scrabled filament density (for each valid pixel)',...
    'Filament orientation (for each pixel)',...
    'Filament orientation (for each pixel,centered)',...
    'Filamet intensity (integrated for each filament)',...
    'Filamet intensity (average for each filament)',...
    'Filamet intensity (integrated for each dilated filament)',...
    'Filamet intensity (average for each dilated filament)',...
    'Scale of detected filaments (for each pixel)',...
    'ST Responce (integrated for each filament)',...
    'ST Responce (average for each filament)',...
    'ST Responce (integrated for each dilated filament)',...
    'ST Responce (average for each dilated filament)',...
    'Filament curvature (average for each filament)',...
    'Filament curvature (for each pixel on filaments)'};

for iF = 1 : 18
    % for the background, plot 25%~50%~75% patch
    % then the mean
    h1 = figure(1); close;
    h1 = figure(1); hold off;
    p = patch([1  nMovie*nFrame/4 nMovie*nFrame/4 1 1],...
        [whole_plate_stat(iF,4) whole_plate_stat(iF,4) whole_plate_stat(iF,6)...
        whole_plate_stat(iF,6) whole_plate_stat(iF,4)],[0.8 0.9 1],...
        'EdgeColor','none','linestyle','none');
    
    hold on;
    %             line1 = plot([1 nMovie*nFrame/4],[whole_plate_stat(iF,1) whole_plate_stat(iF,1)],...
    %                 'm','linewidth',2);
    line2 = plot([1 nMovie*nFrame/4],[whole_plate_stat(iF,4) whole_plate_stat(iF,4)],...
        '-.','color',[0.5 0.5 1]/1.02,'linewidth',2);
    line3 = plot([1 nMovie*nFrame/4],[whole_plate_stat(iF,5) whole_plate_stat(iF,5)],...
        '-','color',[0.5 0.5 1]/1.2,'linewidth',2);
    line4 = plot([1 nMovie*nFrame/4],[whole_plate_stat(iF,6) whole_plate_stat(iF,6)],...
        ':','color',[0.5 0.5 1]/1.02,'linewidth',2);
    
    %             legend([line1, line2,line3,line4],'Mean','25%','Median','50%');
    legend([line2,line3,line4],'25%','Median','50%');
    title(textcell{iF},'fontsize',15);
    
    % for samples
    % plot median for each one
    
    Y = CFMP_feature_ordered_thisCh_perwell(:,:,iF,5);
    plot(Y(:),'*');
end