function [trajSamp,errFlag] = sampleTraj(traj0,sampInt)
%SAMPLETRAJ samples a trajectory generated by simpleMTDIModel at a specified rate
%
%SYNOPSIS [trajSamp,errFlag] = sampleTraj(traj0,sampInt)
%
%INPUT  traj0   : 2-column vector with switching times and lengths at these
%                 times. Output of simpleMTDIModel.
%       sampInt : 1/sampling rate.
%
%OUTPUT trajSamp: Sampled trajectory.
%       errFlag : 0 if function executes normally, 1 otherwise.
%
%Khuloud Jaqaman, May 2005

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%Output
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

trajSamp = [];
errFlag = 0;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%Input
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%check input data
if nargin ~= 2 

    disp('--sampleTraj: Wrong number of input variables!');
    errFlag = 1;
    return

end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%Sampling
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%get total time of original trajectory
totalTime = traj0(end,1);

%calculate number of time points to sample at
numTP = floor(totalTime/sampInt);

%obtain time at which to sample
samplingTime = [0:numTP]'*sampInt;

%get index in traj0 that corresponds to the transition points just before
%each sampling time point.
indxTran = 0;
for i=1:length(traj0)
    indxTran = indxTran + (samplingTime-traj0(i,1)>=0);
end

%reserve memory for trajSamp
trajSamp = zeros(numTP+1,1);

%calculate trajectory value at each sampling point
for i=1:numTP+1
    tmp = traj0(indxTran(i)+1,1) - traj0(indxTran(i),1);
    trajSamp(i) = (traj0(indxTran(i)+1,1)-samplingTime(i))*traj0(indxTran(i),2)/tmp ...
        + (samplingTime(i)-traj0(indxTran(i),1))*traj0(indxTran(i)+1,2)/tmp;
end

%add time column to trajSamp
trajSamp = [samplingTime trajSamp];

%%%%% ~~ the end ~~ %%%%%

