% this "completes" the network training.
% clc;
% clear;
[filename, pathname] = uigetfile('*.mat','Which file to resume from layers checkpoint?',...
                        '/work/bioinformatics/shared/dope/torch/test/217x217/segmented/netTEMP/');
load(fullfile(pathname,filename));

[filename, pathname] = uigetfile('*.mat','Which training set to use?',...
                       '/work/bioinformatics/shared/dope/torch/test/217x217/segmented/');
load(fullfile(pathname,filename));


options = trainingOptions('sgdm',...
        'MaxEpochs',1, ...
        'ValidationFrequency',1000,...
        'MiniBatchSize',100,...
        'Verbose',false,...
        'Plots','training-progress',...
        'ValidationData',imdsValid,...
        'ValidationPatience', Inf,...
        'ExecutionEnvironment' , 'multi-gpu');
    
trainedNet = trainNetwork(imdsTrain,net.Layers,options);

uisave('trainedNet');