function [ err ] = fitArcFromImage(A,di,param)

%This function was created to analyze the size of an arc, generated by an
%axicon, to calculate the effective downstream numerical aperture used to
%create a Bessel beam.  It fits the arc, rather than the entire circle,
%because the arc is typically too large to fit onto the camera.
%Kevin Dean, 2015-11-20.

% param=[-350,-230,857]

%A=double(imread('realigned-afterAnnulus.tiff'));

[ydim,xdim]=size(A);
A=A-min(A(:));
A=A/max(A(:));

cx=param(1);
cy=param(2);
ra=param(3);
B=zeros(ydim,xdim);

err=0;

for k=1:ydim
    for l=1:xdim
        x=l-cx;
        y=k-cy;
        
        r=sqrt(x.^2+y.^2);
        
        if r>ra && r<ra+2
            B(k,l)=1;
        end
        
        
        temp=(A(k,l)-B(k,l))^2;
        err=err+temp;
        
    end
end
if di
    figure
dis=zeros(ydim,xdim,3);
dis(:,:,1)=A;
dis(:,:,2)=B;
imshow(dis,[]);
end


end

